/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.softdev.pokedex.vistas;

import com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme;
import com.softdev.pokedex.modelos.Pokemon;
import java.io.File;
import utils.Adapt;

/**
 *
 * @author university
 */
public class VistaPokemonDetalle extends javax.swing.JFrame {

    Adapt adapt = new Adapt();
    Pokemon pokemon;

    /**
     * Creates new form VistaPokemonDetalle
     */
    public VistaPokemonDetalle(Pokemon pokemon) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.pokemon = pokemon;
        iniciarImagenes();
        cargarPokemon();
    }

    public void iniciarImagenes() {
        String ubicacionActual = System.getProperty("user.dir");
        String rutaRecursos
                = ubicacionActual + File.separator + "src"
                + File.separator + "main" + File.separator + "java" + File.separator + "resources" + File.separator;
        String rutaBanner = rutaRecursos + File.separator + "banner5.jpg";
        
        adapt.setImageLabel(this.bannerPokemon, rutaBanner);
    }
    public void cargarPokemon(){
        adapt.setImageLabel(imgPokemon, MenuPrincipal.obtenerRuta(pokemon.getRutaImagen()));
        String nombreId = pokemon.getNombre()+" | "+MenuPrincipal.obtenerID(pokemon.getId());
        double altura = pokemon.getAltura();
        String descripcion = pokemon.getDescripcion();
        String categoria = pokemon.getCategoria();
        double peso = pokemon.getPeso();
        String habilidad = pokemon.getHabilidad();
        String sexo = pokemon.getSexo();
        int ps = pokemon.getPs();
        int ataque = pokemon.getAtaque();
        int defensa = pokemon.getDefensa();
        int ataqueEspecial = pokemon.getAtaqueEspecial();
        int defensaEspecial = pokemon.getDefensaEspecial();
        int velocidad = pokemon.getVelocidad();

        txtNombre.setText(nombreId);
        txtAltura.setText(String.valueOf(altura));
        txtCategoria.setText(categoria);
        txtPeso.setText(String.valueOf(peso));
        txtDescripcion.setText(descripcion);
        txtHabilidad.setText(habilidad);
        txtSexo.setText(sexo);

        txtAtaque.setText(String.valueOf(ataque));
        txtPs.setText(String.valueOf(ps));
        txtDefensa.setText(String.valueOf(defensa));
        txtAtaqueEspecial.setText(String.valueOf(ataqueEspecial));
        txtDefensaEspecial.setText(String.valueOf(defensaEspecial));
        txtVelocidad.setText(String.valueOf(velocidad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        bannerPokemon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgPokemon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JLabel();
        txtHabilidad = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        txtSexo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JLabel();
        txtPs = new javax.swing.JLabel();
        txtAtaqueEspecial = new javax.swing.JLabel();
        txtDefensaEspecial = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JLabel();
        txtVelocidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pokemon Informacion");
        setMaximumSize(new java.awt.Dimension(1200, 850));
        setMinimumSize(new java.awt.Dimension(1200, 850));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 850));

        background.setMaximumSize(new java.awt.Dimension(1200, 800));
        background.setMinimumSize(new java.awt.Dimension(1200, 800));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        top.add(bannerPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 130));

        background.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 130));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(imgPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(imgPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 540, 400));

        txtNombre.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtNombre.setText("NOMBRE...");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(10);
        txtDescripcion.setRows(5);
        txtDescripcion.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 660, 220));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Peso");

        txtAltura.setText(" ");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Altura");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Habilidad");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Sexo");

        txtCategoria.setText(" ");

        txtHabilidad.setText(" ");

        txtPeso.setText(" ");

        txtSexo.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(txtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltura)
                    .addComponent(txtCategoria)
                    .addComponent(txtHabilidad))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso)
                    .addComponent(txtSexo))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 660, 180));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Puntos de base");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("PS");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("ATAQUE");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 68, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("ATAQUE ESPECIAL");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 68, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("DEFENSA");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 68, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("VELOCIDAD");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 68, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setText("DEFENSA ESPECIAL");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 68, -1, -1));
        jPanel4.add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 124, 40, 30));
        jPanel4.add(txtPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 124, 40, 30));
        jPanel4.add(txtAtaqueEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 116, 40, 38));
        jPanel4.add(txtDefensaEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 106, 40, 40));
        jPanel4.add(txtDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 40, 30));
        jPanel4.add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 40, 30));

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1200, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bannerPokemon;
    private javax.swing.JLabel imgPokemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel top;
    private javax.swing.JLabel txtAltura;
    private javax.swing.JLabel txtAtaque;
    private javax.swing.JLabel txtAtaqueEspecial;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JLabel txtDefensa;
    private javax.swing.JLabel txtDefensaEspecial;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JLabel txtHabilidad;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPs;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
